# Generated by Django 6.0.3 on 2026-04-08 06:59

import apps.restaurants.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cuisine_type', models.CharField(choices=[('it', 'Italian'), ('ch', 'Chinese'), ('in', 'Indian'), ('me', 'Mexican'), ('am', 'American'), ('ja', 'Japanese'), ('th', 'Thai'), ('md', 'Mediterranean')], help_text='Available Cuisine', max_length=2)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999".Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_open', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('minimum_order', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of restaurant', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of restaurant', max_digits=9, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates for distance calculation', null=True, srid=4326)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Restaurant_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('a', 'Appteizer'), ('m', 'Main Course'), ('d', 'Desert'), ('b', 'Beverage'), ('s', 'Side Dish')], help_text='Available Catagories', max_length=1)),
                ('dietary_info', models.CharField(choices=[('v1', 'Vegetarian'), ('v2', 'Vegan'), ('gf', 'Gluten-Free'), ('df', 'Dairy-Free'), ('no', 'None')], help_text='Diteray information', max_length=2)),
                ('is_available', models.BooleanField(default=True)),
                ('preparation_time', models.PositiveIntegerField(default=3)),
                ('foodimage', models.ImageField(blank=True, null=True, upload_to=apps.restaurants.models.MenuItem.file_path)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.Restaurantmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
