# Generated by Django 6.0.3 on 2026-04-15 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0002_alter_menuitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='uprice',
            field=models.DecimalField(decimal_places=2, help_text='snapshot of item price at order time', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('customer', 'order'), name='review_only_once'),
        ),
    ]
