# Generated by Django 6.0.3 on 2026-04-09 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/')),
                ('vehicle_type', models.CharField(blank=True, choices=[('b', 'Bike'), ('s', 'Scooter'), ('c', 'Car')], default='b', help_text="Delivery partner's Vehicle Type", max_length=1)),
                ('vehicle_number', models.CharField(max_length=10, unique=True)),
                ('license_number', models.CharField(max_length=10, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('total_deliveries', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='drive_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
