# Generated by Django 6.0.3 on 2026-04-15 12:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='coordinates for distance calculation', null=True, srid=4326),
        ),
    ]
