# Generated by Django 6.0.3 on 2026-04-07 12:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/')),
                ('loyalty_points', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adrname', models.CharField(help_text='Short name to identify the adress', max_length=60, unique=True)),
                ('address', models.TextField(help_text='Your full address')),
                ('is_default', models.BooleanField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='coordinates for distance calculation', null=True, srid=4326)),
                ('adrofuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_s_adress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/')),
                ('vehicle_type', models.CharField(blank=True, choices=[('b', 'Bike'), ('s', 'Scooter'), ('c', 'Car')], default='b', help_text="Delivery partner's Vehicle Type", max_length=1)),
                ('vehicle_number', models.CharField(max_length=10, unique=True)),
                ('license_number', models.CharField(max_length=10, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('total_deliveries', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
