# Generated by Django 6.0.3 on 2026-04-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customerprofile_alter_customuser_created_at_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
