# Generated by Django 6.0.3 on 2026-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_driverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='utype',
            field=models.CharField(blank=True, choices=[('c', 'Customer'), ('r', 'Restaurant Owner'), ('d', 'Delivery Driver')], default='c', help_text='User Type', max_length=1),
        ),
    ]
